# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bmi.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(461, 512)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #FFF0F5;")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(0, -11, 471, 101))
        self.frame.setStyleSheet("background-color:#FFB6C1")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(60, 30, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setPointSize(24)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #800020;\n"
"background-color: transparent;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btn_calc = QtWidgets.QPushButton(self.centralwidget)
        self.btn_calc.setGeometry(QtCore.QRect(40, 270, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Montserrat Black")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.btn_calc.setFont(font)
        self.btn_calc.setStyleSheet("QPushButton {\n"
"    background-color: #800020;\n"
"    color: #FFFFFF;\n"
"    border-radius: 15px;\n"
"    padding: 10px;\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A00028; /* Чуть светлее при наведении мыши */\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #600018; /* Темнее при нажатии */\n"
"}")
        self.btn_calc.setObjectName("btn_calc")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 130, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #800020;\n"
"font-size: 20pt;\n"
"background-color: transparent;")
        self.label_3.setObjectName("label_3")
        self.input_weight = QtWidgets.QLineEdit(self.centralwidget)
        self.input_weight.setGeometry(QtCore.QRect(70, 170, 111, 71))
        self.input_weight.setStyleSheet("background-color: #FFFFFF;\n"
"border: 7px solid #FFB6C1;\n"
"border-radius: 15px;\n"
"color: #800020;\n"
"padding: 5px;\n"
"font-size: 20pt;")
        self.input_weight.setAlignment(QtCore.Qt.AlignCenter)
        self.input_weight.setObjectName("input_weight")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(270, 130, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #800020;\n"
"font-size: 20pt;\n"
"background-color: transparent;")
        self.label_4.setObjectName("label_4")
        self.input_height = QtWidgets.QLineEdit(self.centralwidget)
        self.input_height.setGeometry(QtCore.QRect(270, 170, 111, 71))
        self.input_height.setStyleSheet("background-color: #FFFFFF;\n"
"border: 7px solid #FFB6C1;\n"
"border-radius: 15px;\n"
"color: #800020;\n"
"padding: 5px;\n"
"font-size: 20pt;")
        self.input_height.setAlignment(QtCore.Qt.AlignCenter)
        self.input_height.setObjectName("input_height")
        self.output_result = QtWidgets.QLabel(self.centralwidget)
        self.output_result.setGeometry(QtCore.QRect(40, 370, 381, 101))
        font = QtGui.QFont()
        font.setFamily("Montserrat SemiBold")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.output_result.setFont(font)
        self.output_result.setStyleSheet("color: #800020;\n"
"font-size: 20pt;\n"
"background-color: transparent;")
        self.output_result.setAlignment(QtCore.Qt.AlignCenter)
        self.output_result.setObjectName("output_result")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Калькулятор ИМТ"))
        self.btn_calc.setText(_translate("MainWindow", "Рассчитать"))
        self.label_3.setText(_translate("MainWindow", "Вес (кг):"))
        self.label_4.setText(_translate("MainWindow", "Рост (м):"))
        self.output_result.setText(_translate("MainWindow", "Результат появится здесь"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
